### ISSUE TITLE
Nodejs12 no longer available

### ISSUE THREAD

**Issue by awsdmitry** [aws-samples/step-up-auth#16]
During the deployment, I get this error:
StepUpAuthApi/Lambda
StepUpAuthApi/Lambda: deploying...
[snip]
StepUpAuthApiLambda981F4013: creating CloudFormation changeset...
3:16:28 PM | CREATE_FAILED        | AWS::Lambda::Function | stepupauthchallengelambda20610070
Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodej
s18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 7a2bec83-a2b7-48cc-acb0-08658724ef21)" (RequestToken: 8af7c4be-d1a9-e135-8b09-235aac9f1c0d,
HandlerErrorCode: InvalidRequest)

There are other issues (cdk v1 is not supported, other warnings, etc) but this is the first error that stops the deployment.

**Comment by smoghal** [comment]
Thanks for the heads-up.  We will publish an updated version with updated node runtime and CDK v2 scripts.  For the time being, you can simply replace all references to `lambda.Runtime.NODEJS_12_X` with `lambda.Runtime.NODEJS_18_X` in CDK code, specifically, [lambda-stack.ts](https://github.com/aws-samples/step-up-auth/blob/main/deployment/lib/api/lambda-stack.ts). The lambda code will work with Node 18 runtime without any change.

**Comment by smoghal** [comment]
Closing the issue.  Please feel free to reopen if you run into problems again.  We will publish CDK v2 upgrade in near future.
